# Generated by Django 5.2.1 on 2025-05-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientes_queixa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='e_mail',
            new_name='email',
        ),
    ]
