# Generated by Django 5.2.1 on 2025-05-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_tarefas_rename_email_pacientes_e_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='e_mail',
            new_name='email',
        ),
    ]
