# Generated by Django 5.2.2 on 2025-07-30 19:25

import django.core.validators
import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_visualizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='foto',
            new_name='paciente_foto',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='pagamento_em_dia',
            new_name='paciente_pagamento_em_dia',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='queixa',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='telefone',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='paciente_email',
            field=models.EmailField(blank=True, help_text='Insira o e-mail: exemplo@exemplo.com', max_length=254, null=True, unique=True, validators=[pacientes.validators.email_validator]),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='paciente_nome',
            field=models.CharField(blank=True, help_text='Insira o nome completo.', max_length=255, null=True, unique=True, validators=[pacientes.validators.name_validator]),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='paciente_queixa',
            field=models.CharField(choices=[('TDAH', 'TDAH'), ('D', 'Depressão'), ('A', 'Ansiedade'), ('TAG', 'Transtorno de Ansiedade Generalizada'), ('T', 'TOC')], default='Queixa', help_text='queixa', max_length=5),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='paciente_telefone',
            field=models.CharField(blank=True, help_text='(0XX)XXXXXXXXX', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='O número deve estar no formato: (011)000000000', regex='^\\d{3}\\d{9}$')]),
        ),
    ]
