# Generated by Django 5.2.2 on 2025-07-30 19:38

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_rename_foto_pacientes_paciente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_email',
            field=models.EmailField(default='sem_email@example.com', help_text='Insira o e-mail: exemplo@exemplo.com', max_length=254, unique=True, validators=[pacientes.validators.email_validator]),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_nome',
            field=models.CharField(default='Sem Nome', help_text='Insira o nome completo.', max_length=255, unique=True, validators=[pacientes.validators.name_validator]),
        ),
    ]
