# Generated by Django 5.2.2 on 2025-07-30 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_pacientes_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_telefone',
            field=models.CharField(blank=True, help_text='(0XX)XXXXXXXXX', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='O número deve estar no formato: (011)000000000', regex='^\\(\\d{3}\\)\\d{9}$')]),
        ),
    ]
