# Generated by Django 5.2.2 on 2025-07-30 19:54

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_alter_pacientes_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_email',
            field=models.EmailField(help_text='Insira o e-mail: exemplo@exemplo.com', max_length=254, unique=True, validators=[pacientes.validators.email_validator]),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_nome',
            field=models.CharField(help_text='Insira o nome completo.', max_length=255, unique=True, validators=[pacientes.validators.name_validator]),
        ),
    ]
