# Generated by Django 5.2.2 on 2025-07-30 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_alter_pacientes_paciente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='tarefas',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='data',
            new_name='paciente_data',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='humor',
            new_name='paciente_humor',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='registro_geral',
            new_name='paciente_registro_geral',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='video',
            new_name='paciente_video',
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente_frequencia',
            field=models.CharField(choices=[('D', 'Diário'), ('1S', '1 vez por semana'), ('2S', '2 vezes por semana'), ('3S', '3 vezes por semana'), ('N', 'Ao necessitar')], default='Frequência', help_text='frequência', max_length=55),
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente_tarefa',
            field=models.CharField(choices=[('Meditação', 'Meditação'), ('Respiração', 'Respiração'), ('Anotação', 'Anotação'), ('Medicação', 'Medicação'), ('Conversação', 'Conversação')], default='Tarefa', help_text='tarefa', max_length=55),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_telefone',
            field=models.CharField(blank=True, help_text='(0XX)XXXXXXXXX', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número deve estar no formato: (011) 000000000', regex='^\\(\\d{3}\\)\\s?\\d{9}$')]),
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
