# Generated by Django 5.2.2 on 2025-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_remove_consultas_tarefas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='paciente_video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
