# Generated by Django 5.2.2 on 2025-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_alter_consultas_paciente_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='paciente_registro_geral',
            field=models.TextField(blank=True, null=True),
        ),
    ]
