# Generated by Django 5.2.2 on 2025-07-31 19:33

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_alter_consultas_paciente_registro_geral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_nome',
            field=models.CharField(error_messages={'unique': 'Já existe um paciente cadastrado com esse nome.'}, help_text='Insira o nome completo.', max_length=255, unique=True, validators=[pacientes.validators.name_validator]),
        ),
    ]
