# Generated by Django 5.2.2 on 2025-07-31 19:35

import django.core.validators
import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_alter_pacientes_paciente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_email',
            field=models.EmailField(error_messages={'unique': 'E-mail já cadastrado.'}, help_text='Insira o e-mail: exemplo@exemplo.com', max_length=254, unique=True, validators=[pacientes.validators.email_validator]),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_telefone',
            field=models.CharField(blank=True, error_messages={'unique': 'Número de telefone já castrado.'}, help_text='(0XX)XXXXXXXXX', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número deve estar no formato: (011) 000000000', regex='^\\(\\d{3}\\)\\s?\\d{9}$')]),
        ),
    ]
