# Generated by Django 5.2.2 on 2025-08-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0018_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='paciente_ref_psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.newuser'),
        ),
    ]
