# Generated by Django 5.2.2 on 2025-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0019_pacientes_paciente_ref_psicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='paciente_queixa',
            field=models.CharField(choices=[('TDAH', 'TDAH'), ('DEPRESSÃO', 'Depressão'), ('ANSIEDADE', 'Ansiedade'), ('TAG', 'Transtorno de Ansiedade Generalizada'), ('TOC', 'TOC')], default='Queixa', help_text='queixa', max_length=15),
        ),
    ]
